### ISSUE TITLE
Remove Escape Strings on the view topic page

### ISSUE THREAD

**Issue by ninenine** [ninenine/nodebb-plugin-beep#21]
The escape characters show up in the title and breadcrumb.
<img width="485" alt="screen shot 2016-10-28 at 5 10 11 pm" src="https://cloud.githubusercontent.com/assets/622901/19809366/b34a50b4-9d31-11e6-8680-869f94fb69ea.png">

**Comment by ninenine** [comment]
resolved by adding a space after the asterisk, doesn't look so good but it works :/

**Comment by julianlam** [comment]
Ah, I see... I've been testing this against composer-redactor, with markdown disabled, hence I didn't notice the regression. I'll research a fix...

**Comment by julianlam** [comment]
@ninenine Is there a reason you needed to add escape characters? I just tried it on my local env, and even with composer-default and markdown re-enabled, the `*`s show up okay.

**Comment by ninenine** [comment]
On my local env, the two asterisks make a character bold. I have the default Nodebb set up from git, maybe it could be something I haven't yet configured :/

<img width="402" alt="screen shot 2016-10-28 at 9 08 08 pm" src="https://cloud.githubusercontent.com/assets/622901/19817202/3f3e5536-9d53-11e6-85a5-f64d9e333583.png">

**Comment by julianlam** [comment]
Yes... that behaviour was my assumption as well, so I was surprised when it *didn't* bold. So at this point it seems like *I'm* the one with the faulty config. I'll keep you apprised...
