### ISSUE TITLE
Illegal/banned words in topic title

### ISSUE THREAD

**Issue by believer** [ninenine/nodebb-plugin-beep#23]
If I type an illegal word in a topic title I don't get an error and the topic is posted. Shouldn't it throw an error like when I type the illegal word inside the content?

If I type a banned word in the topic title it becomes [censored] on the topic page, but the banned word is still visible in the topic listing and anywhere else.

**Comment by ninenine** [comment]
@believer Sorry, I haven't been around, I'll have a look at this tonight.
Also can you tell me which version on of nodebb you are using?

**Comment by ninenine** [comment]
@believer fixed the title error for illegal words here https://github.com/ninenine/nodebb-plugin-beep/commit/35ff1704f1f956937f833472c98edcb1bdac4527

Am not able to replicate your second issue, maybe try reload your nodebb instance when you make changes in the settings? Could you post a screenshot?

**Comment by believer** [comment]
@ninenine no worries, thanks for the title fix! I had an epiphany when you said that you couldn't reproduce the second bug. I'm missing the selector for the title replace (i.e. `component="topic/title"`). My bad, sorry for bothering you with it!

**Comment by ninenine** [comment]
@believer you are welcome :)
