### ISSUE TITLE
Allow plugin to work only on topic pages and not on shoutbox ?

### ISSUE THREAD

**Issue by FaizanZahid** [ninenine/nodebb-plugin-beep#33]
Great Plugin indeed. but has some issues. Please see below.

Can we have a feature so that I can disallow this plugin on the shoutbox page but let it run for posts and topics only?

Also, there is 1 bug in this plugin. When we set the settings to Asterisk, then if a person makes a post using a banned word let's say s e x. then the topic URL also gets * which makes the URL request into infinite re-direction loop and we can then never access that topic via URL. And the whole forum gets hanged on that page. we cant use the forum anymore.

Another bug is that it does not filters words in topic title, i.e it does not say "You cannot use 'BANNED word' in topic title" as it says in topic posts. It lets the user post with a ban word.

When are you guys going to release an update?

**Comment by FaizanZahid** [comment]
Any updates on the redirect infinite loop issue?

**Comment by ninenine** [comment]
@FaizanZahid Damn, year later, Sorry been busy with work and stuff. I have some time now.
Lemme have a look at your request and I'll get back to you.

**Comment by ninenine** [comment]
@FaizanZahid The redirect and title post is already sorted.
As for excluding shoutbox, if you are planning on banning a word it only makes sense to ban it every where.
Am closing this
