### ISSUE TITLE
Bug censoring curse words preceded or followed by a symbol

### ISSUE THREAD

**Issue by stefandz** [ninenine/nodebb-plugin-beep#8]
Just been testing this in a nodebb install - please forgive curse words below, they are to illustrate a specific instance just in case the bug is specific as opposed to general.

With the standard word list, the word fuck becomes f\*\*k as expected. However, one of our users wrote the phrase: fuck-shittty-fuck shit which became fuck-s\*\*ttty-fuck s\*\*t.

Version is 0.1.0

**Comment by ninenine** [comment]
Hmmm, lemme have a look at it. 
It's been a while since I worked on the plugin.

**Comment by stefandz** [comment]
Thank you very much. Let me know if I can help with any testing. By the way, the phrase "Holy shit! Bum, boobs, bugger, wank and felch." ended up as "Holy shit! Bum, boobs, bugger, w**k and felch." even with "felch" added to the list of profane words. It seems that if I punctuate my swearing well I can get a lot through!

**Comment by ninenine** [comment]
Hehe, the assumption was that people with bad grammar are the only ones that curse :)

**Comment by stefandz** [comment]
I realise that my test cases are pretty non-typical! Honestly though, any help I can offer - just let me know :)

**Comment by ninenine** [comment]
Hey man, I don't mind the feedback.
Am using my phone now headed home, will push something in abit.

**Comment by ninenine** [comment]
@stefandz I have refactored the code, hopefully made it better, faster stronger...
Anyways, before I publish it on to npm, could you give it a try and tell me what you think.

**Comment by ninenine** [comment]
Should be working now :)

**Comment by stefandz** [comment]
Hey dude

Sorry to reopen - tried to install this by removing the nodebb-plugins-beep folder from /nodebb/node_modules and replacing with the latest pull. On starting nodebb I get the following error in the log:

```
12/6 10:14 [8294] - error: Error: Cannot find module 'underscore.string'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/ubuntu/nodebb/node_modules/nodebb-plugin-beep/index.js:9:13
    at Object.<anonymous> (/home/ubuntu/nodebb/node_modules/nodebb-plugin-beep/index.js:85:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
12/6 10:14 [8294] - warn: [plugins] Unable to parse library for: nodebb-plugin-beep
```

Is there a node module dependency that I am missing?

**Comment by ninenine** [comment]
you need to run npm install in the /home/ubuntu/nodebb/node_modules/nodebb-plugin-beep/ folder

**Comment by ninenine** [comment]
I have already published it on to npm, so you can ideally just run 
`npm install nodebb-plugin-beep`
in the folder 
`/home/ubuntu/nodebb/`

**Comment by stefandz** [comment]
Thanks - apologies for my ignorance. I keep forgetting important bits of
node! Will try tonight as I am out of office for the rest of today. Thanks
for all your work on this!!

**Comment by stefandz** [comment]
Hi again Davis. Thanks for all your work on this - works perfectly. I tried my very best to curse the code into submission, but it stood tall in defence. Congratulations on a super-useful plugin, and thanks for being approachable.
